### ISSUE TITLE
Auto-generated YouTube CCs

### ISSUE THREAD

**Issue by patrick-wirth** [uwex-learning-tech/sbplus_v3#98]
Example presentation: https://media.uwex.edu/content/msmgt/msmgt760_r19/smgt760_module1/index.html

On the final slide of the presentation, I embedded a TED Talk.  When I view the video on YouTube it has auto-generated captions.  Is it possible for SB to display auto-generated captions on YouTube?

**Comment by Lin87** [comment]
Unfortunately, the video player library (videoJS) and its plugin do not support dynamic/auto-generated captioning capability because a security restriction imposed by Google/YouTube API. Dynamic/auto-generated captioning is one of the advanced features that requires more sophisticated API authentication/token process. VideoJS and its plugins only supports the basic.

The other working around is to have the YouTube embeds (thats requires YouTube advanced playback options) to revert back to YouTube player UI. In previous Ed Tech meeting, we moved this user story to the bottom, but we have a justification to move it back up to the top.

**Comment by Lin87** [comment]
@patrick-wirth This should be resolved by the recent feature that allows caption for YouTube video when using the default player.
